dist: xenial
language: python
python:
  - "3.7"
service:
  - docker
install:
  - pip install -e .
  - pip install codecov
script:
  - coverage run setup.py test
  - tests/e2e/run.sh tests/e2e/compose/chrome.yml
  - tests/e2e/check_result.sh
  - tests/e2e/run.sh tests/e2e/compose/firefox.yml
  - tests/e2e/check_result.sh
  - tests/e2e/run.sh tests/e2e/compose/chrome-hook.yml
  - tests/e2e/check_hook_logs.sh
after_success:
  - codecov
